language: node_js
node_js: node
# so that chrome works
# see https://github.com/video-dev/hls.js/pull/1710#discussion_r187754754
sudo: required
# don't connect to sauce labs unless running functional tests
before_install: if [ "${TRAVIS_MODE}" != "funcTests" ]; then unset SAUCE_USERNAME && unset SAUCE_ACCESS_KEY; fi
script: ./scripts/travis.sh
after_script: if [ "${TRAVIS_MODE}" = "funcTests" ]; then echo -n "travis_fold:start:sauce_logs\nSauce connect log:\n" && cat /home/travis/sauce-connect.log && echo -n "\ntravis_fold:end:sauce_logs\n"; fi
env:
  global:
    - SAUCE_USERNAME=robwalch
    - secure: qrWlTSEwJOU+CvHSBgJR3gOVP9Tf+zFYHaU5wiMoxetE1EfNPTkvqxQSZcqwEGFo0kXfqk7HvbJq5GvOwwRbkecxdTrNKHKJ6YkD0zlkFhiZIO3p6mWJadD5OPnYvxD5OIEUhDZgtN1pSmOEi1hwC5dEH2q4+tVLS3V7EdzHMSjBYfY9zfPwCsb6eRZCy6Gf+YrS7eiQGG/+hVgr264yx+p038vJIOG76Y++i+RYeP6A5N5U654Xqf7AkEJQZ8ULVcq54rJUAFtP4Jys16I6JiCCR4n3C+eW1eAemTlOfGAddCP+SbgNjfde6jHgXUx5VOXrln12KR/ohVbi7vt0Q+rnpFgs2NpaMI3/5f3NPRlG9jbeeJBhLO3P3swSomdnbfOwgirJN+JhGQ33lsTC72ggGk1G5SmDhnZ2NVipYnSGLLLS4OmauyXQHqsL3okxFLQR0iM1w08RtrpRuvou7bH1a3WsBN9MZf/8oI9hgG2AtdhtKpqVu1z2U9X+TluJwljxtegCZC2t12LU9JbHqcLOsd12s8ApWAZegYpGMx3nguz0gYmiXqBnKf3jye9CWraOcHBavhfD4U7eMR8i3bdIQR3Hs/xLsNSw7+TRRLYJA+vi3q/enPSChf3driViL6KT+dUSABbBncZk4iNhJXUwrmKUhZns6xTscEU2DNI=
stages:
  - buildAndTest
  - releaseAlpha
  - release
  - testFuncRequired
  - testFuncOptional
jobs:
  # stage: optional is allowed to be failure
  fast_finish: true
  allow_failures:
    - stage: testFuncOptional
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    # publish package (and deploy gh-pages)
    - stage: release
      if: tag IS present
      env: TRAVIS_MODE=release
      deploy:
        provider: releases
        api_key:
          secure: "kR9xHKhWfOv6vwxz1d//PpC22VDupnPI59L9czLkpLoIdzm5rm3eV7he4XPlQfbSrV1UBgURARgF+yekmeqUZk9vqfo4F5oa+6KiBxAdnI9PjsjYRSXitdq4a6kpIR854nxUIOlDXR5AbD2MgNaKsQHiaNlngdR/870OhiwqRJVwQOLKVUADw1QWECXe/DXrQiFbMunxBrTyutbrGuI8cT7wzqFn+aPkI/3liiw8PTr93GrtxZ/bFxI899KzMSHHMXB+eDDMtxPFD+VApruD7h6f+1C0psJeOV8/PkzrRkbPELPBKKaPH9TvVOPUf2OSRHVna828wnLHwseae0rgtuk7+ZJmB9XZKX9FUBDT4/Gv/AkE+m/cwnoqaatAMJYR+yiQqsosjBLDAaTUOPHu3wBdAaR5uL5fGsSsKe3sUfSQHrv86vReNl9ETU06apmyWtsIbyhMtv98j9I+hNVjKZUI30g1ee6LgjlDlBavMk8KAbLbyBTcJlNAexj8Rppdqg+AdW7rYW+S6SgfTyyYQKTLeFwmDjfrkqzHJnk78sV18+xPLI1hbzBGp/bXaW23sLDBLLV5Sxifr8flUMkUdH28zsLCHUQ7C4GKQ19el2NZgIxSsnxRA8vGZof7OXasR4HJVjv/PSx+DN6Fi1PV1SiNBcwgPCGIIxBF7TUPxJk="
        file_glob: true
        file: dist/*.{js,js.map}
        draft: true
        tag_name: $TRAVIS_TAG
        target_commitish: $TRAVIS_COMMIT
        skip_cleanup: true
        on:
          tags: true
    # publish canary package if on master
    - stage: releaseAlpha
      if: branch = master AND type != pull_request
      env: TRAVIS_MODE=releaseAlpha
    # Required tests
    - stage: buildAndTest
      env:   TRAVIS_MODE=build
    - stage: buildAndTest
      env:   TRAVIS_MODE=unitTests
    - stage: testFuncRequired
      env:   TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"
    # Optional Func tests
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=chrome              OS="Windows 7"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=firefox             OS="Windows 7"
    # - stage: testFuncOptional
    #  env:   TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1"  UA_VERSION="11.0"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 10"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=chrome              OS="OS X 10.11"
    # - stage: testFuncOptional
    #  env:   TRAVIS_MODE=funcTests UA=firefox     OS="OS X 10.11"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.12" UA_VERSION="10.1"
addons:
  sauce_connect: true
